# Generated by Django 4.1.2 on 2022-10-18 17:47

import django.core.validators
from django.db import migrations, models
import pets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('species', models.CharField(choices=[('cat', 'cat'), ('dog', 'dog'), ('hamster', 'hamster')], default='cat', max_length=50)),
                ('year_of_birth', models.PositiveIntegerField(default=2022, validators=[django.core.validators.MinValueValidator(1950), pets.models.max_value_current_year])),
            ],
        ),
    ]
